#!/bin/bash

usage()
{
    echo "usage: `basename $0` -u USER -h HOST -p PASSWORD -d DATABASE
    -u      user
    -h      host
    -p      password
    -d      database
    --help  show this message
    "
    exit
}

OPT=`getopt -o u:h:p:d: --long help -- "$@"`
if [ $? -ne 0 -o "$1" = "" ]; then
    usage
fi
eval set -- "$OPT"

while true
do
    case "$1" in
        -u )
            MYSQL_USER=$2
            shift 2
            ;;
        -h )
            MYSQL_HOST=$2
            shift 2
            ;;
        -p )
            MYSQL_PASS=$2
            shift 2
            ;;
        -d )
            MYSQL_DATABASE=$2
            shift 2
            ;;
        --help )
            usage
            ;;
        -- )
            break
            ;;
        * )
            echo "Unknown parameter $1"
            usage
            ;;
    esac
done

if [ "$MYSQL_USER" = "" -o \
     "$MYSQL_HOST" = "" -o \
     "$MYSQL_PASS" = "" -o \
     "$MYSQL_DATABASE" = "" ]; then
    usage
fi

mysql -u$MYSQL_USER -h$MYSQL_HOST -p$MYSQL_PASS $MYSQL_DATABASE -N -e "show tables" \
    | xargs -I{} bash -c "
        echo {};
        mysql -u$MYSQL_USER -h$MYSQL_HOST -p$MYSQL_PASS $MYSQL_DATABASE -e 'desc {}';
        echo" \
    | sed 's/\t/,/g'

